# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llml < Formula
  desc "Terminal UI to discover local models and launch llama-server or vLLM"
  homepage "https://github.com/flyingnobita/llml"
  version "0.2.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.6/llml_0.2.6_Darwin_x86_64.tar.gz"
      sha256 "9010fd41b7687eed29f89d0ebfaaaebeacb6d501c857d0adcbebabf76c82ab47"

      define_method(:install) do
        bin.install "llml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.6/llml_0.2.6_Darwin_arm64.tar.gz"
      sha256 "a44bb04f8bfb795c7e0f743bfe82c589b9692ab339a5bc7f938fcea9f83a37a8"

      define_method(:install) do
        bin.install "llml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.6/llml_0.2.6_Linux_x86_64.tar.gz"
      sha256 "e0398756296e365e5ba7fe02692f3664295cb34d28bfb283ece13d5ad6051d9d"
      define_method(:install) do
        bin.install "llml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flyingnobita/llml/releases/download/v0.2.6/llml_0.2.6_Linux_arm64.tar.gz"
      sha256 "39e2c3c7dd9d84891787b69352d34e44d1ba0f5a48d66743919400a9c09dc996"
      define_method(:install) do
        bin.install "llml"
      end
    end
  end
end
